name: Dart Client Generation

on:
  workflow_run:
    workflows: [Quality Assurance]
    types: [completed]
    branches: [main, dart-client-generation]

jobs:
  dart_client_generation:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./app-controller
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Restore tools
      run: dotnet tool restore
    - name: Generate OpenAPI file
      run: |
        dotnet swagger tofile `
          --output openapi.json `
          ".\IntelliCook.AppController.Api\bin\Release\net8.0\IntelliCook.AppController.Api.dll" `
          v0.1
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
    - name: Activate OpenAPI Generator
      run: dart pub global activate openapi_generator_cli
    - uses: actions/checkout@v4
      working-directory: ./app-controller-client
      with:
        ref: dart-client
    - name: Remove old files
      run: git rm -r '*'
    - name: Generate Dart client
      run: |
        openapi-generator generate `
          -i openapi.json `
          -g dart-dio `
          -o ../app-controller-client/ `
          -p pubName="app_controller_client" `
          -p pubLibrary="app_controller_client.api"
    - name: Commit and push
      working-directory: ./app_controller_client
      run: |
        git config --global user.name "Dart Client Generation"
        git config --global user.email "username@users.noreply.github.com"
        git add .
        git status
        git commit --verbose -m "Dart Client"
        git status
        git push --verbose
        