name: Dart Client Generation

on:
  workflow_run:
    workflows: [Quality Assurance]
    types: [completed]
    branches: ["main"]

jobs:
  dart_client_generation:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: app-controller
    
    steps:
    - uses: actions/checkout@v4
      with:
        path: app-controller
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add Auth Source
      run: dotnet nuget add source "https://nuget.pkg.github.com/NAMESPACE/index.json" `
        --name github `
        --name "Quality Assurance" `
        --username "username@users.noreply.github.com" `
        --password ${{ secrets.GITHUB_TOKEN }} `
        --store-password-in-clear-text
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Restore tools
      run: dotnet tool restore
    - name: Checkout Dart client branch
      uses: actions/checkout@v4
      with:
        ref: dart-client
        path: app-controller-client
    - name: Remove old files
      working-directory: app-controller-client
      run: git rm -r '*'
    - name: Generate OpenAPI file
      run: |
        dotnet swagger tofile `
          --output ../app-controller-client/openapi.json `
          ./IntelliCook.AppController.Api/bin/Release/net8.0/IntelliCook.AppController.Api.dll `
          v0.1
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Activate OpenAPI Generator
      run: dart pub global activate openapi_generator_cli
    - name: Generate Dart client
      working-directory: app-controller-client
      run: |
        openapi-generator generate `
          -i openapi.json `
          -g dart-dio `
          -o ./ `
          -p pubName="app_controller_client" `
          -p pubLibrary="app_controller_client.api"
        dart run build_runner build --delete-conflicting-outputs
    - name: Commit and push
      working-directory: app-controller-client
      run: |
        git config --global user.name "Dart Client Generation"
        git config --global user.email "username@users.noreply.github.com"
        git add .
        git status
        git commit --verbose -m "Dart client ${{ github.sha }}"
        git status
        git push --verbose
        